version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/docker-py:$CIRCLE_BRANCH .
      - run: docker push $DOCKER_USER/docker-py:$CIRCLE_BRANCH
